# Generated by Django 5.2.1 on 2025-06-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_date', models.DateField()),
                ('de_title', models.CharField(max_length=255)),
                ('de_content', models.TextField()),
                ('de_emoState', models.CharField(max_length=50)),
                ('de_emoScore', models.IntegerField()),
                ('de_advice', models.TextField(blank=True, null=True)),
                ('de_isDelete', models.BooleanField(default=False)),
                ('de_editCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_name', models.CharField(max_length=100)),
                ('ft_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_dob', models.DateField()),
                ('user_gender', models.CharField(max_length=10)),
                ('user_createAt', models.DateTimeField(auto_now_add=True)),
                ('user_avatarUrl', models.CharField(blank=True, max_length=300, null=True)),
                ('user_interests', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('di_imageUrl', models.CharField(max_length=300)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fe_content', models.TextField()),
                ('fe_submitedAt', models.DateTimeField(auto_now_add=True)),
                ('fe_isResolve', models.BooleanField(default=False)),
                ('feedback_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.feedbacktype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_content', models.TextField()),
                ('re_createAt', models.DateTimeField(auto_now_add=True)),
                ('re_isSent', models.BooleanField(default=False)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.diaryentry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
            ],
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='tags',
            field=models.ManyToManyField(related_name='entries', through='api.DiaryTag', to='api.tag'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_title', models.CharField(max_length=50)),
                ('rm_content', models.TextField()),
                ('rm_date', models.DateField()),
                ('rm_isSent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='api.user'),
        ),
    ]
