# Generated by Django 5.2.1 on 2025-07-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_password_user_password_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='de_emoScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='de_emoState',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
