# Generated by Django 5.2.1 on 2025-07-21 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_diaryentry_de_emoscore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='rm_isSent',
        ),
        migrations.AddField(
            model_name='reminder',
            name='rm_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='rm_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='rm_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
