# Generated by Django 5.2.1 on 2025-08-05 03:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_reminder_rm_issent_reminder_rm_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='di_imageUrl',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
