# Generated by Django 5.2.1 on 2025-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_diaryimage_di_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='fe_title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
